### ISSUE TITLE
Missing modifications (specifically TMT)

### ISSUE THREAD

**Issue by Arthfael** [rformassspectrometry/unimod#11]
Unless I am doing something wrong, it seems that the package's database has not been updated in several years?

```
> devtools::install_github("rformassspectrometry/unimod", upgrade = TRUE, force = TRUE)
> require(unimod)
> UniMod <- unimod::modifications
> max(UniMod2$UnimodId)
[1] 1979

```
If I check in Unimod, there are now 2072 modifications. Unfortunately for me right now, the few ones which are missing include TMTpro :D It would be great to get an update.
Otherwise, thanks for a very useful package!

**Comment by sgibb** [comment]
While this is one interesting package it is unfortunately neglected and not developed for a long time. 
We are hindering ourselves by our ambition to create the perfect package for all kind of modifications and mass calculation.
Maybe we should remove all the complicated calculation stuff and reduce the package to a simple interface for the unimod database and finally release it in a usable shape.

However I upgraded the datasets to the latest unimod version.

**Comment by lgatto** [comment]
Thank you @sgibb - could we automate this? Do we have a script of documentation of the upgrade process somewhere?

**Comment by Arthfael** [comment]
*"We are hindering ourselves by our ambition to create the perfect package
for all kind of modifications and mass calculation."* Boy does it sound
familiar! ;D

Thank you very much for the update ^^
I do not know how people use this package, in my case, I mainly use it to
access the Unimod table. (For instance, I use it mostly to convert DIA-NN
and FragPipe psm tables to a MaxQuant evidence.txt-like table with the old
"Modified sequence" column format, since for historical reasons all my
workflows expect the latter output). I would expect that any additional
package functionality, while nice to have, would be secondary for most
users. Definitely having a script which captures automatically new Unimod
releases and updates the package would be great!

Anyway, thanks guys, for this and all your many other useful contributions
to the R-based Proteomics community!
Kind regards,

Armel

**Comment by sgibb** [comment]
> Thank you @sgibb - could we automate this? Do we have a script of documentation of the upgrade process somewhere?

Sure. It's in `?modifications`:

In theory it is just
```r
devtools::load(); devtools::wd(); unimod:::.createDataSets()
```
(in reality it didn't work because the newly added unimod IDs weren't unique and I had to add some lines to create unique IDs)
